# Generated by Django 5.1.3 on 2024-12-08 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='path',
            field=models.CharField(max_length=1024),
        ),
    ]
