# Generated by Django 5.1.2 on 2024-12-06 09:51

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time_uploaded', models.DateTimeField(default=datetime.datetime.now, verbose_name='time uploaded')),
                ('url', models.URLField(max_length=1024)),
                ('alt_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=256, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('time_joined', models.DateTimeField(default=datetime.datetime.now, verbose_name='time joined')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time_published', models.DateTimeField(default=datetime.datetime.now, verbose_name='time published')),
                ('loc_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('loc_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.image')),
                ('tags', models.ManyToManyField(to='home.tag')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.user')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_positive', models.BooleanField()),
                ('time_rated', models.DateTimeField(default=datetime.datetime.now, verbose_name='time rated')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.report')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time_posted', models.DateTimeField(default=datetime.datetime.now, verbose_name='time posted')),
                ('text', models.CharField(max_length=256)),
                ('report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.report')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.user')),
            ],
        ),
    ]
