# Generated by Django 5.1.3 on 2024-12-08 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_comment_user_alter_rating_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='url',
        ),
        migrations.AddField(
            model_name='image',
            name='path',
            field=models.FilePathField(default='idk/lol', max_length=1024),
            preserve_default=False,
        ),
    ]
