name: Generate GitHub Metrics

on:
  schedule: 
    - cron: '0 0 * * *'  # Runs every day at midnight
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: tilkynntu-is  # Your GitHub username
          template: classic
          config_timezone: Europe/Reykjavik
          plugin_contributors: yes
          plugin_activity: yes
          plugin_languages: yes
          plugin_stars: yes
